spring:
  application:
    name: spring-redis
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_redis
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      data-locations: classpath:script.sql
      mode: always
  jpa:
    show-sql: true
