spring:
  application:
    name: spring-redis
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:5432/${PGDB:spring_redis}
    username: ${PGUSER:postgres}
    password: ${PGPASS:123}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      data-locations: classpath:script.sql
      mode: always
  jpa:
    show-sql: true
  data:
    redis:
      port: ${CACHEPORT:6379}
      host: ${CACHEHOST:localhost}
  cache:
    type: redis
